name: Build CV PDF

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: danteev/texlive:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build PDF
        run: make
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: NaqashNaveed_CV.pdf
          path: NaqashNaveed_CV.pdf
      - name: Create Release and Upload PDF
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: NaqashNaveed_CV.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
